### ISSUE TITLE
Check the compatibility with Python 3.X  i.e Python 3.5

### ISSUE THREAD

**Issue by developeralgo8888** [zhongwen/predictron#10]
Conda latest is running python 3.5.2 

example 

import Queue  ==> Python 2.7 

i am not sure if you tested it with python 3.X  , it has  a couple of errors

Please can you make sure it is compatible with TF 0.12.1 and Python 3.5 at least .

**Comment by zhongwen** [comment]
Hey, please `git pull` again. no more `import Queue` in the py3 branch. Also, I have merged the py3 into the master. I have tested it.

**Comment by zhongwen** [comment]
Please use `train_multigpu.py`. I will apply a simple fix on the `train.py`. Please do use the environment file I have provided to make sure we are using the same environment.

**Comment by zhongwen** [comment]
Here is the logs I obtained just:
```
INFO:predictron:iter/conv3/BatchNorm/gamma
INFO:predictron:iter/conv3/preact/beta
INFO:predictron:******************************
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:89:00.0)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2501 get requests, put_count=1772 evicted_count=1000 eviction_rate=0.564334 and unsatisfied allocation rate=0.731307
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
INFO:training:2017-01-20 13:29:03.915630: step 0, loss = 6.7586, loss_preturns = 2.1931, loss_lambda_preturns = 1.1714 (10.2 examples/sec; 12.491 sec/batch)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2501 get requests, put_count=2864 evicted_count=2000 eviction_rate=0.698324 and unsatisfied allocation rate=0.660936
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 176 to 193
INFO:training:2017-01-20 13:29:47.370831: step 10, loss = 2.6130, loss_preturns = 0.7997, loss_lambda_preturns = 0.4916 (284.0 examples/sec; 0.451 sec/batch)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 0 get requests, put_count=1030 evicted_count=1000 eviction_rate=0.970874 and unsatisfied allocation rate=0
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2501 get requests, put_count=2385 evicted_count=1000 eviction_rate=0.419287 and unsatisfied allocation rate=0.469812
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 655 to 720
INFO:training:2017-01-20 13:29:51.927408: step 20, loss = 1.8465, loss_preturns = 0.5627, loss_lambda_preturns = 0.3450 (285.6 examples/sec; 0.448 sec/batch)
INFO:training:2017-01-20 13:29:56.534957: step 30, loss = 1.5707, loss_preturns = 0.4832, loss_lambda_preturns = 0.2863 (280.6 examples/sec; 0.456 sec/batch)
```

Python version:
```
➜  predictron git:(master) ✗ python --version
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
```

**Comment by developeralgo8888** [comment]
Why dont you use conda latest with all the latest packages including Python 3.5.2 & TF 0.12.1 instead of trying to reinvent the wheel. I am using train_multigpu.py  as you indictaed but i still get the error


python ./train_multigpu.py --max_depths=16 --batch_size=128 --num_gpus=8


Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 589, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("Placeholder:0", shape=(?, 20, 20, 1), dtype=float32, device=/device:CPU:0)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train_multigpu.py", line 249, in <module>
    tf.app.run()
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./train_multigpu.py", line 245, in main
    train()
  File "./train_multigpu.py", line 145, in train
    maze_ims_splits = tf.split(0, FLAGS.num_gpus, maze_ims_ph)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1222, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3426, in _split
    num_split=num_split, name=name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
^CException ignored in: <module 'threading' from '/home/anaconda3/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/home/anaconda3/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/home/anaconda3/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by zhongwen** [comment]
OK, man. I have used conda, and install the TF 0.12.1 following exactly the same steps showing in the webpage of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#anaconda-installation. I have pointed this page to you in the previous issue. 

So sorry that I cannot reproduce your error.

**Comment by developeralgo8888** [comment]
i just pulled the py3 tree as per your earlier post and got that error above

**Comment by zhongwen** [comment]
I promised I have used py3.5 and TF 0.12.1 and cannot reproduce your error.

```
(tensorflow) ➜  predictron git:(master) ✗ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
tf.>>> tf.__version__
'0.12.1'
>>>
```

Please confirm your TF version. Also, please try to fix the error.

**Comment by developeralgo8888** [comment]
are you running a virtual conda environment as a docker or as a default environment on a linux distro

**Comment by zhongwen** [comment]
In the host. Not a docker

**Comment by zhongwen** [comment]
And inside conda.

**Comment by developeralgo8888** [comment]
ok , i am also running inside a host not a docker . running exactly same version as yours

**Comment by zhongwen** [comment]
I cannot help on this. I did not see the error on my side. Please confirm the TF version. That's the only thing I can think of.

**Comment by developeralgo8888** [comment]
should i pull the py3 tree or the master

**Comment by zhongwen** [comment]
master please.

**Comment by developeralgo8888** [comment]
TF version is 0.12.1

**Comment by zhongwen** [comment]
Well, I think you may try to figure out the error on your side. Sorry about that.

**Comment by zhongwen** [comment]
You may try `train.py`. Your error is caused by the `split` function in `train_multigpu.py`.

**Comment by developeralgo8888** [comment]
# split the large batch arcoss all towers
    maze_ims_splits = tf.split(0, FLAGS.num_gpus, maze_ims_ph)
    maze_labels_splits = tf.split(0, FLAGS.num_gpus, maze_labels_ph)


that's where the error is. i recall you did change that piece of code in previous tree

**Comment by developeralgo8888** [comment]
H, the issue is caused by the API change,

from r0.12.1's

tf.split(split_dim, num_split, value, name='split')
to r1.0alpha's

tf.split(value, num_or_size_splits, axis=0, num=None, name='split')	
You may modify it into your TF version's API accordingly.

**Comment by zhongwen** [comment]
I changed concat. Have u tried the train.py ? That one does not include the
split function

**Comment by developeralgo8888** [comment]
i use multi_GPUs, i have 8 Pascal Titan X

**Comment by zhongwen** [comment]
Modify it and make it runnable on your side. I can run the current version
on my side. I will update the repo after 1.0 is released

**Comment by developeralgo8888** [comment]
tf.split(split_dim=0, num_split=FLAGS.num_gpus, value = maze_ims_ph, name='split')
to r1.0alpha's

tf.split(value = maze_ims_ph, num_or_size_splits = FLAGS.num_gpus, axis=0, num=None, name='split')

not sure but would this be the correct modification:

tf.split( maze_ims_ph , FLAGS.num_gpus, axis=0 )

**Comment by developeralgo8888** [comment]
tf.split( maze_ims_ph , FLAGS.num_gpus, 0 )

**Comment by developeralgo8888** [comment]
Replaced outdated tf.pack with tf.stack

**Comment by developeralgo8888** [comment]
updated 
     #losses.add_loss(self.loss_preturns)
      tf.losses.add_loss(self.loss_preturns)
      tf.summary.scalar('loss_preturns', self.loss_preturns)
      # Loss Eqn (7)
      self.loss_lambda_preturns = tf.losses.mean_squared_error(
      self.g_lambda_preturns, self.targets, scope='lambda_preturns')
      tf.losses.add_loss(self.loss_lambda_preturns)
      tf.summary.scalar('loss_lambda_preturns', self.loss_lambda_preturns)
      self.total_loss = tf.losses.get_total_loss(name='total_loss')

**Comment by zhongwen** [comment]
Please send a PR instead of mentioning the changes one-by-one, PR would be a much more efficient way.

**Comment by developeralgo8888** [comment]
ok , i will send that once i can run it successfully. i just tried it but got an error . I will may be look at it later 




Traceback (most recent call last):
  File "./train_multigpu.py", line 253, in <module>
    tf.app.run()
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./train_multigpu.py", line 249, in main
    train()
  File "./train_multigpu.py", line 162, in train
    config)
  File "./train_multigpu.py", line 61, in tower_loss
    model.build()
  File "/Developer/Downloads/predictron-master/predictron.py", line 57, in build
    self.build_model()
  File "/Developer/Downloads/predictron-master/predictron.py", line 105, in build_model
    state = slim.conv2d(self.inputs, 32, [3, 3], scope='conv1')
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 885, in convolution
    input_rank)
ValueError: ('Convolution not supported for input with rank', 0)
